# Generated by Django 5.1.7 on 2025-03-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pokemon_id', models.IntegerField(unique=True)),
                ('image', models.URLField()),
                ('type', models.CharField(max_length=255)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('move', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
